# Generated by Django 5.0.6 on 2024-06-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_remove_student_confirm_password_remove_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='book_images/')),
            ],
        ),
    ]
