# Generated by Django 5.0.6 on 2024-06-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0007_acceptedbookrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedbookrequest',
            name='book',
        ),
        migrations.RemoveField(
            model_name='acceptedbookrequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='acceptedbookrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='acceptedbookrequest',
            name='details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libapp.bookrequest'),
        ),
    ]
